# Generated by Django 4.2.16 on 2024-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='criterion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
