# Generated by Django 4.2.16 on 2025-02-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False)),
                ('criterion', models.TextField(blank=True, max_length=1000, null=True)),
                ('questions', models.TextField(blank=True, max_length=1000, null=True)),
                ('grades', models.IntegerField(blank=True, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course')),
            ],
        ),
    ]
