# Generated by Django 4.2.16 on 2025-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_course_name_course_semester_remove_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='data',
            name='program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
