# Generated by Django 4.2.16 on 2025-03-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_data_file_data_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_content', models.TextField(blank=True, null=True)),
                ('criterion', models.TextField(blank=True, max_length=1000, null=True)),
                ('questions', models.TextField(blank=True, max_length=1000, null=True)),
                ('grades', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
