# Generated by Django 4.2.16 on 2025-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_uploadeddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='data',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='data',
            name='questions',
        ),
        migrations.AddField(
            model_name='data',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
