# Generated by Django 4.2.16 on 2025-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_data_criterion_remove_data_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
