# Generated by Django 4.2.16 on 2025-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddata',
            name='criterion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddata',
            name='grades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddata',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
