# Generated by Django 4.2.16 on 2025-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_uploadeddata_criterion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
